---
format:
  docx:
    reference-doc: t.docx
---

##### Durango, Dgo., a 04 de septiembre de 2025.
<br><br>

# Dra. Claudia Campillo Toledano  
# Universidad de Chile  
<br><br>

Estimada Dra. Campillo Toledano:  

Por este medio, me complace invitarle a participar como ponente en el **Panel “Cartografías del bienestar”**, que se desarrollará en el marco de la **8ª Semana Nacional de las Ciencias Sociales**, organizada por el Consejo Mexicano de Ciencias Sociales (COMECSO).  

El evento tendrá lugar el próximo **15 de octubre de 2025, a las 17:00 horas (modalidad en línea, vía Zoom)**. El objetivo es generar un espacio de análisis y reflexión sobre los principales desafíos para el bienestar de las poblaciones en México y América Latina desde una visión de complejidad, proponiendo perspectivas de acción desde la academia, la política pública y la sociedad civil.  

Nos honraremos con su participación en este encuentro junto con colegas de reconocida trayectoria.  

Sin más, reciba un cordial saludo.  

<br><br>

### Atentamente,  

<br><br><br>

### Dr. Jorge Enrique Bracamontes Grajeda  
#### Líder del Cuerpo Académico CA UJED-140  
#### Facultad de Trabajo Social, UJED  
