---
format:
  docx:
    reference-doc: cartaCA.docx
---

<br><br><br>

### ACTA DE REUNIÓN DE CUERPO ACADÉMICO

<br><br><br>

# Fecha y lugar
En la ciudad de Durango, Dgo., siendo las **17:00hrs.** del **6 de noviembre de 2025**, se reunieron los integrantes del Cuerpo Académico **“Estudios Sociales y del Bienestar” (CA UJED-140)**, adscrito a la **Facultad de Trabajo Social de la Universidad Juárez del Estado de Durango (UJED)**, con el propósito de tratar el punto establecido en el orden del día.

<br>

# Integrantes presentes
- **Dr. Jorge Enrique Bracamontes Grajeda**  
- **Dra. Perla Vanessa De los Santos Amaya**  
- **M.A. Marcela Cordero Pérez**

<br>

# Orden del día
Único punto:  
**Definir quién de los integrantes del Cuerpo Académico UJED-140 será designado como representante ante el Consejo de Investigación de la Facultad de Trabajo Social de la UJED.**

<br>

# Desarrollo de la reunión
Durante la sesión, las y los integrantes del cuerpo académico analizaron la importancia de contar con un representante que funja como enlace entre el Cuerpo Académico y el Consejo de Investigación de la Facultad, a fin de fortalecer la vinculación, el seguimiento de proyectos y la participación en las actividades académicas y de investigación institucionales.

Después de la deliberación correspondiente, se procedió a la **designación de la persona representante del CA UJED-140**.

<br>

# Acuerdo
Por unanimidad, se **acordó que la M.A. Marcela Cordero Pérez** será la **representante del Cuerpo Académico “Estudios Sociales y del Bienestar” (CA UJED-140)** ante el **Consejo de Investigación de la Facultad de Trabajo Social de la UJED**.

# Cierre
No habiendo más asuntos que tratar, se dio por concluida la reunión, firmando para constancia las y los integrantes del cuerpo académico en la fecha indicada.

<br><br>

## ANUENCIA DE LES INTEGRANTES  

<br><br><br>

||||
|:---:|:---:|:---:|
|**Dr. Jorge Enrique Bracamontes Grajeda**|**Dra. Perla Vanessa de los Sabntos Amaya**|**M.A. Marcela Cordero Pérez**| 
|*Líder del CA UJED-140*|*Miembra del CA UJED-140*|*Miembra del CA UJED-140*|