---
format:
  docx:
    reference-doc: cartaCA.docx
---

<br><br><br>

##### Durango, Dgo., a 07 de noviembre de 2025.
<br><br>

# DRA. ANA ROSA RODRÍGUEZ DURÁN  
# Directora de la Facultad de Trabajo Social
# Universidad Juárez del Estado de Durango
<br><br>


Por medio del presente, me permito informarle que en reunión del **Cuerpo Académico “Estudios Sociales y del Bienestar” (CA UJED-140)**, integrada por la **Dra. Perla Vanessa De los Santos Amaya**, la **M.A. Marcela Cordero Pérez** y un servidor, **Dr. Jorge Enrique Bracamontes Grajeda**, se acordó por unanimidad designar a la **M.A. Marcela Cordero Pérez** como **representante del cuerpo académico ante el Consejo de Investigación de la Facultad de Trabajo Social de la UJED**.

Sin otro particular, y reiterando nuestro compromiso con el fortalecimiento de las actividades de investigación en nuestra Facultad, quedo de usted para cualquier aclaración o seguimiento correspondiente.

<br><br>

### Atentamente: 

<br><br><br>

### Dr. Jorge Enrique Bracamontes Grajeda  
#### Líder del Cuerpo Académico CA UJED-140  
#### Facultad de Trabajo Social, UJED  
